# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ICS-Simple
version:      0.04
version_from: lib/ICS/Simple.pm
installdirs:  site
requires:
    ICS:                           0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
